services:
  api:
    build:
      context: .
      target: dev
    container_name: fc26_api
    depends_on:
      - redis
    env_file:
      - .env.local
    environment:
      REDIS_URL: redis://redis:6379
    ports:
      - "3333:3333"
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma

  db:
    image: postgres:16-alpine
    container_name: fc26_db
    environment:
      POSTGRES_USER: fc26
      POSTGRES_PASSWORD: fc26
      POSTGRES_DB: fc26_career_hub
    ports:
      - "5432:5432"
    volumes:
      - fc26_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: fc26_redis
    ports:
      - "6380:6379"

  influxdb:
    image: influxdb:1.8-alpine
    container_name: fc26_influxdb
    environment:
      INFLUXDB_DB: k6
      INFLUXDB_DATA_MAX_SERIES_PER_DATABASE: 0
    ports:
      - "8086:8086"
    volumes:
      - fc26_influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: fc26_grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - fc26_grafana_data:/var/lib/grafana
      - ./load-test/grafana/provisioning:/etc/grafana/provisioning

volumes:
  fc26_data:
  fc26_influxdb_data:
  fc26_grafana_data:
