import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse } from 'csv-parse/sync'

type WorksheetRow = {
  appClub: string
  appLeague: string
  suggestedFitScoreClub: string
}

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const worksheetPath = resolve(process.argv[2] ?? 'data/fit-score-club-alias-updated - Worksheet.csv')
const outputPath = resolve('src/shared/utils/fit-score-club-aliases.generated.ts')
const defaultArtifactsDir = resolve(repoRoot, '..', 'fit-score-svc', 'artifacts')
const defaultPython =
  process.platform === 'win32'
    ? resolve(repoRoot, '..', 'fit-score-svc', '.venv', 'Scripts', 'python.exe')
    : resolve(repoRoot, '..', 'fit-score-svc', '.venv', 'bin', 'python')

const artifactsDir = resolve(process.env.FIT_SCORE_ARTIFACTS_DIR ?? defaultArtifactsDir)
const pythonBin = resolve(process.env.FIT_SCORE_PYTHON ?? defaultPython)

if (!existsSync(worksheetPath)) {
  throw new Error(`Worksheet not found at ${worksheetPath}`)
}

if (!existsSync(pythonBin)) {
  throw new Error(`Python not found at ${pythonBin}. Set FIT_SCORE_PYTHON to the fit-score-svc venv python.`)
}

if (!existsSync(resolve(artifactsDir, 'club_profiles.pkl'))) {
  throw new Error(`club_profiles.pkl not found in ${artifactsDir}. Set FIT_SCORE_ARTIFACTS_DIR.`)
}

const rows = parse(readFileSync(worksheetPath, 'utf8'), {
  columns: true,
  bom: true,
  skip_empty_lines: true,
}) as WorksheetRow[]

const serviceClubNames = loadServiceClubNames()
const aliases = new Map<string, Map<string, string>>()
const invalidRows: WorksheetRow[] = []

for (const row of rows) {
  if (!row.appClub || !row.appLeague || !row.suggestedFitScoreClub) continue

  if (!serviceClubNames.has(row.suggestedFitScoreClub)) {
    invalidRows.push(row)
    continue
  }

  if (!aliases.has(row.appLeague)) aliases.set(row.appLeague, new Map())
  aliases.get(row.appLeague)!.set(row.appClub, row.suggestedFitScoreClub)
}

if (invalidRows.length) {
  const details = invalidRows
    .slice(0, 20)
    .map((row) => `${row.appClub} (${row.appLeague}) -> ${row.suggestedFitScoreClub}`)
    .join('\n')
  throw new Error(`Some suggestedFitScoreClub values were not found in club_profiles.pkl:\n${details}`)
}

writeFileSync(outputPath, renderAliases(aliases), 'utf8')

const aliasCount = Array.from(aliases.values()).reduce((total, leagueAliases) => total + leagueAliases.size, 0)
console.log(`Generated ${aliasCount} aliases in ${outputPath}`)

function loadServiceClubNames(): Set<string> {
  const code = `
import json
import pickle
import sys
from pathlib import Path

profiles_path = Path(sys.argv[1]) / "club_profiles.pkl"
with profiles_path.open("rb") as f:
    club_profiles = pickle.load(f)

print(json.dumps(sorted({key[0] for key in club_profiles}), ensure_ascii=False))
`

  const output = execFileSync(pythonBin, ['-c', code, artifactsDir], {
    encoding: 'utf8',
    env: { ...process.env, PYTHONIOENCODING: 'utf-8' },
    maxBuffer: 1024 * 1024 * 10,
  })

  return new Set(JSON.parse(output) as string[])
}

function renderAliases(aliasesByLeague: Map<string, Map<string, string>>): string {
  const lines = [
    '// Generated by scripts/sync-fit-score-club-aliases.ts.',
    '// Edit data/fit-score-club-alias-updated - Worksheet.csv, then run npm run fit-score:clubs:sync.',
    'export const MANUAL_CLUB_NAME_BY_LEAGUE_MAP: Record<string, Record<string, string>> = {',
  ]

  for (const league of Array.from(aliasesByLeague.keys()).sort((a, b) => a.localeCompare(b))) {
    lines.push(`  ${JSON.stringify(league)}: {`)
    const leagueAliases = aliasesByLeague.get(league)!

    for (const appClub of Array.from(leagueAliases.keys()).sort((a, b) => a.localeCompare(b))) {
      lines.push(`    ${JSON.stringify(appClub)}: ${JSON.stringify(leagueAliases.get(appClub))},`)
    }

    lines.push('  },')
  }

  lines.push('}')
  lines.push('')

  return lines.join('\n')
}
